name: todo_mobile
version: 1.0.0+1
description: A modern production-ready Flutter Todo app.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  fl_chart: ^0.68.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  adaptive_icon_background: '#6750A4'
  adaptive_icon_foreground: assets/images/app_icon.png

flutter_native_splash:
  color: '#F4EDFF'
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: '#F4EDFF'
